pretrained_model_path: "/mnt/petrelfs/liuwenran/repos/diffusers/resources/stable-diffusion-v1-5"
output_dir: "./outputs/bmx-rider"

train_data:
  video_path: "/mnt/petrelfs/liuwenran/datasets/loveu-tgve-2023/DAVIS_480p/480p_frames/bmx-rider"
  prompt: "A person does a trick on a BMX bike at a skatepark."
  n_sample_frames: 32
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  prompts:
    - "A person does a trick on a unicycle at a skatepark."
  video_length: 32
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 1000
validation_steps: 500
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True